prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "package",
    "dotnet",
    "golang",
    "java",
    "nodejs",
    "php",
    "python",
    "ruby",
    "rust",
    "elixir",
    "terraform",
    "kubernetes",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "time",
    "character",
]


[git_branch]
symbol = " "
style = "bold red"

[character]
symbol = " "
vicmd_symbol = " "

[elixir]
symbol = " "

[aws]
disabled = true

[nodejs]
symbol = " "

[package]
disabled = true

[kubernetes]
prefix = "within"
disabled = false
symbol = " "
